### PR TITLE
Fixed error on deleting root nodes

### PR DESCRIPTION
**Pull request by bspanoghe**
Fix for issue #68 
Also added the root node deletion case to tests

### CODE REVIEW

**Comment by VEZY** [comment]
Thanks @bspanoghe ! I merged your PR and triggered a patch release. The new version should be available in under an hour.

**Comment by bspanoghe** [comment]
You're very welcome! I've been working on my own FSPM-related Julia package which interfaces with this package to deal with the plant structure and it has been utmost useful. I did stumble on what seem to be a few more bugs in the meantime. Would it be easiest for you if I open these as separate issues and make a single PR for all of them?

**Comment by VEZY** [comment]
It's great to hear the package has been useful for your FSPM work. Thanks for letting me know! Is your project open source? 

For the bugs, opening separate issues would be ideal. A single PR to address them all sounds good too, if they are related. If not so related, a PR per issue would be even better. 

Appreciate your help!

Just in case, I also develop PlantSimEngine, which is a package that is supposed to help modelers in developing FSP models (or simpler models). It is still WiP but should have all base functionality ready to use. Let me know if it can be of interest for you, and if I can be of any help. We are currently developing an FSPM for Oil Palm with it, and any new use case is more than welcome! The kind of short term objective is to provide a "library of models" for future developers, and let PlantSimEngine do the hard work of model coupling and parallelisation. One example is PlantBiophysics, which is a collection of ecophysiological models.

**Comment by bspanoghe** [comment]
That's great, I'll open them as separate issues and PR's shortly then

And thank you for your interest in my project! The intent is indeed to make it an open-source Julia package called PlantModules.jl.
The basic idea is to allow users to input a plant structure as a graph (which is what I'm here for!) and then define how different node types (e.g. leaf, internode or root) behave functionally by linking them to sets of differential equations. The package then generates the ODE system for the entire plant, generating a subsystem for every node and linking them together as defined in the graph. All of which is possible because of Julia's wonderful modeling environment. ModelingToolkit.jl really does all the heavy lifting.

You may be pleased to hear that I'm currently working on adding support to more easily integrate with PlantSimEngine.jl for defining the meteorological conditions and using its functional models. If you would be interested in helping with the integration of the package with PlantSimEngine, that would of course be more than welcome - together with Alejandro Morales you seem to be responsible for almost all of the FSPM-related packages in Julia. I'm hoping to have the package in a presentable state by the end of the month, I can tag you if you'd like?

Kind regards

**Comment by VEZY** [comment]
We discussed ODEs + PlantSimEngine with @tdeswaef during and after the 2023 FSPM conference. Unfortunately, I didn't find time to work on it. So, I'm really glad that someone is looking into it and making it open for the community. This is great news! 

Feel free to tag me whenever you want or need my help. Also, don't hesitate to make any proposals. I'm still figuring out the design of PlantMeteo and PlantSimEngine (although most changes I had in mind happened recently), so there is room for changes and improvements.

**Pull request merged**
